[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
offline = false
solc_version = "0.8.24"
fs_permissions = [
    { access = "read", path = "./out/" },
    { access = "read", path = "./broadcast/" },
]
